---
title: "Creating Final Data"
author: "Eugenio Paglino"
date: "\today"
output:
  html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
# Loading necessary packages
library(readxl)
library(here)
library(magrittr)
library(ggthemes)
library(tidyverse)

# Set seed for the Rmd
set.seed(42)
```

```{r}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/cleanTractData.Rmd')
inDir <- here('data','input')
outDir <- here('data','output')
```

```{r}
deaths <- read_excel(here(inDir,'Mass_Tract_Deaths_2017-2021_25JUL2023.xlsx'))
pop <- read_csv(here(inDir,'DECENNIALDP2020.DP1_2023-09-28T075102','DECENNIALDP2020.DP1-Data.csv'))
```

```{r}
deaths <- deaths %>% 
  rename(tractCode=TRACTCODE10,ageStr=age,deaths=DEATHS) %>%
  mutate(tractCode=as.character(tractCode),
         x=as.integer(str_match(ageStr,'\\d+')),
         x=if_else(ageStr=='<1 years',0,x)) %>%
  mutate(x=if_else(x<5,0,x)) %>%
  group_by(tractCode,x) %>%
  summarise(deaths=sum(deaths)) %>%
  ungroup()
```

```{r}
deaths <- deaths %>%
  rowwise() %>%
  mutate(
    deathsRB3 = case_when(
      deaths %% 3 == 0 ~ deaths,
      deaths %% 3 == 1 ~ sample(c(deaths+2,deaths-1),size=1,prob = c(1/3,2/3)),
      deaths %% 3 == 2 ~ sample(c(deaths-2,deaths+1),size=1,prob = c(1/3,2/3))
      )
    )
```

```{r}
shapefile <- sf::read_sf(here(inDir,'tl_2020_25_tract','tl_2020_25_tract.shp'))
shapefile <- shapefile %>%
  filter(ALAND>0) %>%
  select(tractCode=GEOID,
         name=NAMELSAD)
```

```{r}
shapefile <- shapefile %>%
  left_join(
    deaths %>%
      group_by(tractCode) %>%
      summarise(deaths=sum(deaths),
                deathsRB3=sum(deathsRB3)) %>%
      ungroup(),
    by='tractCode'
  )
```

```{r}
shapefileJoined <- shapefile %>%
  mutate(
    tractCode = if_else(
      is.na(deaths) & !str_ends(tractCode,'0'),
      str_c(str_sub(tractCode,start=0,end=nchar(tractCode)-1),'0'),
      tractCode
      ),
    name = str_glue(
      'Census Tract {str_sub(tractCode,nchar(tractCode)-5,nchar(tractCode)-2)}.{str_sub(tractCode,nchar(tractCode)-1,nchar(tractCode))}'
      )
    ) %>%
  group_by(tractCode,name) %>%
  summarise(deaths=sum(deaths),
            deathsRB3=sum(deathsRB3)) %>%
  ungroup() %>%
  select(-c(deaths,deathsRB3))
```

```{r}
popCols <- names(pop)[str_detect(as.vector(pop[1,]),'^Count!!SEX AND AGE!!Total population!![\\w\\s]*?[\\d]+')]
popCols <- c(c('GEO_ID','NAME'),popCols)
pop <- pop %>% 
  select(all_of(popCols))

colNames <- str_match(as.vector(pop[1,]),'^Count!!SEX AND AGE!!Total population!!([\\w\\s]+)')[,2]
colNames[1:2] <- c('geoID','name')

names(pop) <- colNames

pop <- pop %>%
  slice_tail(n=nrow(pop)-2) %>%
  pivot_longer(cols=colNames[-c(1:2)],names_to = 'ageStr',values_to = 'pop') %>%
  mutate(x=as.integer(str_match(ageStr,'\\d+')),
         x=if_else(ageStr=='Under 5 years',0,x),
         tractCode = str_remove(geoID,'1400000US'),
         pop=as.numeric(pop)) %>%
  select(tractCode,x,pop)
```

```{r}
ltData <- pop %>%
  left_join(deaths,by=c('tractCode','x')) %>%
  mutate(tractCode = if_else(is.na(deaths) & !str_ends(tractCode,'0'),
                             str_c(str_sub(tractCode,start=0,end=nchar(tractCode)-1),'0'),
                             tractCode)) %>%
  group_by(tractCode,x) %>%
  summarise(pop=sum(pop)) %>%
  ungroup() %>%
  left_join(deaths,by=c('tractCode','x'))
```

```{r}
shapefileJoined <- shapefileJoined %>%
  left_join(
    ltData %>%
      group_by(tractCode) %>%
      summarise(deaths=sum(deaths),
                deathsRB3=sum(deathsRB3),
                pop=sum(pop)) %>%
      ungroup(),
    by='tractCode'
  )
```

```{r}
dataMap <- shapefileJoined %>%
  ggplot() +
  geom_sf(mapping=aes(fill=log(deaths/pop))) +
  labs(fill='Log(CDR)') +
  theme_map()

dataMap
```

```{r}
library(leaflet)

pal <- colorNumeric("Blues", NULL)

shapefileJoined %>% 
  sf::st_transform('+proj=longlat +datum=WGS84') %>%
  filter(str_detect(name,'Census Tract 8\\d{3}'),
         !is.na(deaths)) %>%
  mutate(logCDR = log(deathsRB3/pop)) %>%
  filter(!is.infinite(logCDR)) %>%
  leaflet() %>% 
  setView(lng = -72.0589, lat = 42.3601, zoom = 8) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, 
              smoothFactor = 0.3,
              fillOpacity = 0.8,
              fillColor = ~pal(logCDR)) %>%
  addLegend(pal = pal, values = ~logCDR, opacity = 0.8)
```

```{r}
ltData %>% write_csv(here(outDir,'ltTractData.csv'))
```

```{r}
ltData %>%
  left_join(shapefileJoined %>% sf::st_drop_geometry() %>% select(tractCode,name), by='tractCode') %>%
  filter(str_detect(name,'Census Tract 8\\d{3}')) %>%
  select(-deaths) %>%
  rename(deaths=deathsRB3) %>%
  write_csv(here(outDir,'ltTractMWData.csv'))
```